[package]
name = "tyme-server"
version = "0.1.0"
edition = "2021"

[dependencies]
paho-mqtt = "0.12"
env_logger = "*"
futures = "0.3"
futures-timer = "3.0"
tokio = { version = "1", features = ["full"] }
anyhow = "*"
lazy_static = "*"
parking_lot = "*"
serde = { version = "*", features = ["derive"] }
serde_json = "*"
toml_edit = { version = "0.20", features = ["serde"] }
axum = { version = "0.6" }
nanoid = "0.4"
tower = { version = "0.4", features = ["full"] }
tower-http = { version = "0.4", features = ["fs", "trace"] }
axum-sessions = "0.5"
tokio-util = { version = "0.7", features = ["io"] }


[dev-dependencies]
axum-macros = "*"
