[mqtt_config]
broker = "k37bbe35.ala.cn-hangzhou.emqxsl.cn"
port = 8883
client_id = "test"
keep_alive_interval = 60
topics = [{ topic = "command/#", qos = 1 }, { topic = "chat/#", qos = 1 }]
version = 5
lwt = "Im offline"

[mqtt_config.auth]
enable = true
username = "leri"
password = "R7ddsQxAGchQPQB"

[mqtt_config.ssl]
enable = true
trust_store = "./ssl/emqxsl-ca.crt"

[web_console_config]
public = true
username = "root"
password = "FxL3nw70"
port = 12566
api_token = "1uY-1MPhNtIzQ1NK"