log_location = "./log"

[mqtt_config]
broker = "k37bbe35.ala.cn-hangzhou.emqxsl.cn"
port = 8883
client_id = "tyme-server-0"
keep_alive_interval = 60
topics = ["test","hello"]
version = 5

[mqtt_config.lwt]
topic = "LWT"
qos = 1

[mqtt_config.lwt.content]
type = "MarkDown"
text = "[LWT] I'm go"

[mqtt_config.auth]
enable = true
user_name = "leri"
password = "R7ddsQxAGchQPQB"

[mqtt_config.ssl]
enable = true
trust_store = "./ssl/emqxsl-ca.crt"

[web_console_config]
public = true
user_name = "root"
password = "FxL3nw70"
port = 12566
front_end_path = "./tyme-console/dist"
api_token = "1uY-1MPhNtIzQ1NK"
