[package]
name = "cron_task"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2"
quote = "1.0.9"
cron = "0.12.0"

[lib]
proc-macro = true
